Repository Logius-standaarden/OAuth-NL-profiel, pull requests merged in 2024-05, with the labels that each got.

#45 PR: Public clients MUST apply PKCE
  Client Profiles.md
Labels: bug, Scope: Klein, Status: In review, Type: Correctie, Overleg: TO-OAuth

#43 PR: Rfc8705 toegevoegd
  Advanced OAuth Security Options.md
  Authorization Server Profile.md
  Client Profiles.md
Labels: Scope: Klein, Status: Klaar voor release, Type: Wijziging, Overleg: TO-OAuth

#33 PR: Allow direct access clients to authenticate with an X.509 certi…
  Client Profiles.md
Labels: Scope: Klein, Status: In review, Type: Wijziging, Overleg: TO-OAuth

#40 PR: Authorization servers SHOULD support dynamic client registration
  Authorization Server Profile.md
Labels: Scope: Klein, Status: In review, Type: Correctie, Overleg: TO-OAuth
